### PR TITLE
URI.regex | Added IPv6 compatibility

### PR DESCRIPTION
**Pull request by boppy**
Related to: https://github.com/mootools/mootools-more/issues/1318

Added basic recognition of IPv6 addresses to the regex by adding a second option the the host-part of the regex (starting with index 66+18 byte).
Does not check syntax anyhow. Only checking for "[", "]" wrapping "any mass off" [a-fA-F0-9:].

### CODE REVIEW

**Comment by arian** [comment]
This looks very nice!

**Comment by timwienk** [comment]
:+1:

Small change, does exactly what it should (syntax checking the IPv6 address would make it too slow for hardly any benefit). Thanks for adding the test as well.

Also ++ on the style fix commit.

**Comment by ngosang** [comment]
Thanks.

**Comment by cristscott89** [comment]
Amazing! This is an excellent paragraph, and it has provided me with numerous clear ideas.  [Hronestop Att/begin](https://hronestopatts.com/)

**Pull request merged**
