### PR TITLE
Fix for Issue #1159

### LINKED ISSUE #1159: Drag.move disables input text edit mode.
Here is a simple script. I pasted it on jsfiddle and tried it. Drag works but can not enter value to input box.
Same code works fine on IE but issue is in FireFox and chrome. 

HTML:

```
<div id='popup' class='popwin'>
    <div id='header' class='header'> </div>
    <div id='prop_input' > < input id='input' value='enter value'> </input> </div>
</div>
```

CSS:
```
#popup {
  background-color: #fff;
  border: 1px solid #303030;
  float: left;
  top:500px;    
  width: 30%;
  height:100px;
}

#header {
  background-color: #4422ff;
  border: 1px solid #808080;
  float: left;
  width: 99%;
  height:20px;
  cursor:'move';
}
```

JS:

```
var popwin = $$('.popwin');
$$('.header').setStyle('cursor', 'move');
var dragme = function(event) {
    var draga = new Drag.Move(this, {
    });
    draga.start(event);
};
popwin.addEvent('mousedown', dragme);
```

Test case on  jsfiddle.net

http://jsfiddle.net/CvGcb/4/

<bountysource-plugin>
---
Want to back this issue? **[Post a bounty on it!](https://www.bountysource.com/issues/359755-drag-move-disables-input-text-edit-mode?utm_campaign=plugin&utm_content=tracker%2F22069&utm_medium=issues&utm_source=github)** We accept bounties via [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F22069&utm_medium=issues&utm_source=github).
</bountysource-plugin>

### PR DESCRIPTION
**Pull request by tomahim**
Solution based on what is done on the Sortable class. Fixes #1159

### CODE REVIEW

**Comment by SergioCrisostomo** [comment]
lgtm. @arian @anutron can I merge this?

**Comment by arian** [comment]
Yes, seems ok, maybe some tests would be nice.

**Comment by SergioCrisostomo** [comment]
@arian would this be a ok test?: https://github.com/SergioCrisostomo/mootools-more/commit/8416e901ba40f529a58552e2112b87424b3126ae

The failing test: http://jsfiddle.net/CvGcb/14/
The passing test: http://jsfiddle.net/CvGcb/15/

**Comment by anutron** [comment]
Looks good to me. As a side note, I'd put the conditional on one line. We don't break lines like that in MooTools.

**Comment by SergioCrisostomo** [comment]
Fixed in https://github.com/mootools/mootools-more/commit/fa1acb1a216b2595abe04bf132ba8f77a7d1ae91

**Pull request closed without merging**
