### PR TITLE
Allow international special characters in emails - fixes #1305

### LINKED ISSUE #1305: Allow common international special characters in emails
The [validate-email Regex](https://github.com/mootools/mootools-more/blob/master/Source/Forms/Form.Validator.js#L487) in Form.Validator blocks special characters that are common in international languages (such as `áéíèàùñÑêÊäÄöÖüÜçÇ`).

Demo: http://jsfiddle.net/bhstahl/sju4nson/2/

<bountysource-plugin>
---
Want to back this issue? **[Post a bounty on it!](https://www.bountysource.com/issues/11294066-allow-common-international-special-characters-in-emails?utm_campaign=plugin&utm_content=tracker%2F22069&utm_medium=issues&utm_source=github)** We accept bounties via [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F22069&utm_medium=issues&utm_source=github).
</bountysource-plugin>

### PR DESCRIPTION
**Pull request by bhstahl**
The validate-email Regex in Form.Validator blocks special characters that are common in international languages (such as áéíèàùñÑêÊäÄöÖüÜçÇ).

Bug demo: http://jsfiddle.net/bhstahl/sju4nson/2/

Refs #1305

### CODE REVIEW

**Comment by DimitarChristoff** [comment]
well. this is not alpha numeric. if we go that route, all of these need to
pass as per RFC6530


   - Latin Alphabet (with diacritics): Pelé@example.com
   - Greek Alphabet: δοκιμή@παράδειγμα.δοκιμή
   - Traditional Chinese Characters: 我買@屋企.香港
   - Japanese Characters: 甲斐@黒川.日本
   - Cyrillic Characters: чебурашка@ящик-с-апельсинами.рф


On Thursday, April 16, 2015, Ben Stahl <notifications@github.com> wrote:

> ------------------------------
> You can view, comment on, or merge this pull request online at:
>
>   https://github.com/mootools/mootools-more/pull/1306
> Commit Summary
>
>    - Allow international special characters in emails - fixes #1305
>
> File Changes
>
>    - *M* Source/Forms/Form.Validator.js
>    <https://github.com/mootools/mootools-more/pull/1306/files#diff-0> (4)
>    - *M* Specs/Forms/Form.Validator.js
>    <https://github.com/mootools/mootools-more/pull/1306/files#diff-1> (5)
>
> Patch Links:
>
>    - https://github.com/mootools/mootools-more/pull/1306.patch
>    - https://github.com/mootools/mootools-more/pull/1306.diff
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/mootools/mootools-more/pull/1306>.
>


-- 
Dimitar Christoff

"JavaScript is to JAVA what hamster is to ham"
@D_mitar - https://github.com/DimitarChristoff

**Comment by timwienk** [comment]
See my comments at https://github.com/mootools/mootools-more/issues/1305

**Comment by DimitarChristoff** [comment]
exactly. furthermore. HTML5's `input[type=email]` without a supplied
pattern also fails in the same way, which is OK as you can configure it.

On Thursday, April 16, 2015, Tim Wienk <notifications@github.com> wrote:

> See my comments at #1305
> <https://github.com/mootools/mootools-more/issues/1305>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/mootools/mootools-more/pull/1306#issuecomment-93806248>
> .
>


-- 
Dimitar Christoff

"JavaScript is to JAVA what hamster is to ham"
@D_mitar - https://github.com/DimitarChristoff

**Comment by bhstahl** [comment]
@timwienk @DimitarChristoff Very fair points, I agree with your stance. It was a use case localized fix for a legacy project, so I figured I would contribute but hand't considered your points. If I get some time the `validate-email-advanced` validator would be a nice solution.

**Pull request closed without merging**
